### PR TITLE
Small fixes on how we think about enums

### PR DESCRIPTION
**Pull request by frojasg**
* fix assignations 
* fix map_reduce call
* fix parameters in assert_raise expectation

### CODE REVIEW

**Comment by frojasg** [comment]
I don't have a problem to change the function syntax. Could you elaborate a little bit why do you prefer this style please. Thanks

**Comment by apieum** [comment]
Yes of course, I prefer the fn syntax because it is easier to understand for someone learning elixir.
It makes clear that you need a function as the second argument (which is how it is documented).
When you don't know elixir it's not obvious that &(&1 == 2) is a function.

**Comment by frojasg** [comment]
it makes a lot of sense. Thanks for the feedback

**Comment by frojasg** [comment]
@apieum Could you take a look now please. Thanks!

**Comment by apieum** [comment]
It's perfect for me, thanks a lot.

**Pull request merged**
